import{loadCatalog}from'./data.js';
import{findMatches}from'../ai/matching.js';
import{loadState,saveState,clearState,addHistory,exportableState,mergeImportedState}from'./store.js';
import{exportJSON,importJSON}from'./export.js';

const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const documentNames={experience:'Lettre d’expérience',information:'Relevé d’information',licence:'Permis de conduire',claims:'Historique des sinistres',translation:'Traduction',address:'Preuve d’adresse',policy:'Ancien contrat'};
const documentWeights={experience:16,information:14,licence:14,claims:14,translation:14,address:14,policy:14};
const statusNames={missing:'Document manquant',available:'Document disponible',translation:'Traduction nécessaire',renew:'Document à renouveler'};
let catalog,state=loadState(),lastMatches=[],lastInput=null,compareSelection=[],activeWorkspace='profile';

function toast(message){const node=$('#toast');node.textContent=message;node.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.hidden=true,2800)}
function country(id){return catalog.countries.find(item=>item.id===id)}
function company(id){return catalog.companies.find(item=>item.id===id)}
function activeProfile(){return state.profiles.find(item=>item.id===state.activeProfileId)||state.profiles[0]}
function profileDocuments(){const id=activeProfile().id;return state.documentsByProfile[id]||(state.documentsByProfile[id]={experience:'missing',information:'missing',licence:'missing',claims:'missing',translation:'missing',address:'missing',policy:'missing'})}
function readiness(documents=profileDocuments()){return Object.entries(documentWeights).reduce((score,[id,weight])=>score+(documents[id]==='available'?weight:0),0)}
function statusBadge(item){if(item.verified)return'<span class="badge verified">Vérifié</span>';if(item.status==='pending')return'<span class="badge pending">À confirmer</span>';return'<span class="badge demo">Démonstration</span>'}

function populate(){const countryOptions=catalog.countries.map(item=>`<option value="${item.id}">${item.flag} ${escapeHTML(item.name)}</option>`).join(''),coverageNames={'third-party':'Responsabilité civile','extended-third-party':'Tiers étendu','comprehensive':'Tous risques','premium-comprehensive':'Tous risques premium'},vehicleNames={compact:'Compacte',sedan:'Berline',suv:'SUV',electric:'Véhicule électrique',premium:'Véhicule premium',utility:'Utilitaire'};$('#origin-country').insertAdjacentHTML('beforeend',countryOptions);$('#destination-country').insertAdjacentHTML('beforeend',countryOptions);$('#current-company').insertAdjacentHTML('beforeend',catalog.companies.map(item=>`<option value="${item.id}">${escapeHTML(item.name)}</option>`).join(''));$('#coverage-type').insertAdjacentHTML('beforeend',catalog.coverages.map(item=>`<option value="${item.id}">${escapeHTML(coverageNames[item.id]||item.name)}</option>`).join(''));$('#vehicle-type').innerHTML=catalog.vehicles.map(item=>`<option value="${item.id}">${escapeHTML(vehicleNames[item.id]||item.name)}</option>`).join('');$('#coverage-type').value='comprehensive';$('#vehicle-type').value='compact';renderProfileOptions();applyProfileToForm()}
function renderProfileOptions(){const select=$('#profile-select'),current=state.activeProfileId;select.innerHTML=state.profiles.map(item=>`<option value="${escapeHTML(item.id)}">Profil ${escapeHTML(item.name)}</option>`).join('')+'<option value="new">Nouveau profil</option>';select.value=current}
function applyProfileToForm(){const profile=activeProfile(),form=$('#comparison-form');$('#origin-country').value=profile.originCountry;$('#destination-country').value=profile.destinationCountry;$('#current-company').value=profile.id==='julia'?'julia-assurance':'pirez-assurance';form.elements.insuredYears.value=profile.insuredYears??0;const docs=profileDocuments();form.elements.hasExperienceLetter.checked=docs.experience==='available';form.elements.hasInformationStatement.checked=docs.information==='available';form.elements.hasClaimsHistory.checked=docs.claims==='available';updateIdentity()}

function readForm(){const form=$('#comparison-form'),input=Object.fromEntries(new FormData(form));for(const key of['hasExperienceLetter','hasInformationStatement','hasClaimsHistory'])input[key]=form.elements[key].checked;input.mainDriver=true;input.youngDriver=false;return input}
function validate(input){const errors=[];for(const key of['originCountry','destinationCountry','currentCompany','insuredYears','bonusMalus','claimsCount','coverageType'])if(input[key]===''||input[key]==null)errors.push('Veuillez compléter tous les champs principaux.');if(input.originCountry===input.destinationCountry)errors.push('Les pays d’origine et de destination doivent être différents.');if(Number(input.insuredYears)<0||Number(input.insuredYears)>60)errors.push('L’ancienneté doit être comprise entre 0 et 60 ans.');if(Number(input.claimsCount)<0||Number(input.claimsCount)>20)errors.push('Le nombre de sinistres doit être compris entre 0 et 20.');return[...new Set(errors)]}

function resultCard(match){const logo=match.company.logo||'./assets/logos/bonusbridge-symbol.svg',selected=compareSelection.includes(match.company.id);return`<article class="insurer-card"><img src="${escapeHTML(logo)}" alt="Logo ${escapeHTML(match.company.name)}"><div><span>${escapeHTML(country(match.rule.destinationCountry)?.name||match.rule.destinationCountry)} · ${match.recognized?'Historique accepté*':'Non accepté*'}</span><h3>${escapeHTML(match.company.name)}</h3></div><dl><div><dt>Compatibilité</dt><dd>${match.score}/100</dd></div><div><dt>Années reconnues</dt><dd>${match.recognizedYears} max.</dd></div><div><dt>Bonus conservé</dt><dd>${match.recognizedBonus}%*</dd></div><div><dt>Traduction</dt><dd>${match.translationRequired?'Requise*':'Non*'}</dd></div></dl>${statusBadge(match)}<div class="result-actions"><button type="button" data-favorite="${escapeHTML(match.company.id)}">${state.favorites.includes(match.company.id)?'Retirer le favori':'Favori'}</button><label><input type="checkbox" data-compare="${escapeHTML(match.company.id)}" ${selected?'checked':''}> Comparer</label></div></article>`}
function bindResultActions(){$$('[data-favorite]',$('#result-grid')).forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.favorite)));$$('[data-compare]',$('#result-grid')).forEach(input=>input.addEventListener('change',()=>toggleComparison(input.dataset.compare,input.checked)))}
function renderResults(matches,input,{save=true}={}){const grid=$('#result-grid'),summary=$('#results-summary');lastMatches=matches;lastInput=input;compareSelection=compareSelection.filter(id=>matches.some(match=>match.company.id===id));if(!matches.length){summary.textContent='Aucune règle locale disponible pour ce trajet.';grid.innerHTML='<article class="empty-state"><strong>Aucun scénario disponible.</strong><p>Ce résultat ne signifie pas que votre historique sera refusé. Contactez directement les assureurs de destination.</p></article>';renderComparisonTable();return}summary.textContent=`${matches.length} scénario${matches.length>1?'s':''} de démonstration · meilleur score ${matches[0].score}/100`;grid.innerHTML=matches.slice(0,6).map(resultCard).join('');bindResultActions();renderComparisonTable();if(save){addHistory(state,`${country(input.originCountry)?.name} → ${country(input.destinationCountry)?.name}`,`${input.originCountry}-${input.destinationCountry}`,matches[0].score,input,matches[0].company.id);renderWorkspace('history')}}
function toggleComparison(id,checked){if(checked&&!compareSelection.includes(id)){if(compareSelection.length>=3){toast('Trois assureurs maximum');renderResults(lastMatches,lastInput,{save:false});return}compareSelection.push(id)}else if(!checked)compareSelection=compareSelection.filter(item=>item!==id);renderComparisonTable()}
function renderComparisonTable(){const box=$('#comparison-table'),matches=compareSelection.map(id=>lastMatches.find(item=>item.company.id===id)).filter(Boolean);if(!matches.length){box.innerHTML='<p>Sélectionnez jusqu’à trois assureurs dans les résultats pour les comparer.</p>';return}const row=(label,values)=>`<tr><th>${label}</th>${values.map(value=>`<td>${value}</td>`).join('')}</tr>`;box.innerHTML=`<div class="table-scroll"><table><thead><tr><th>Critère</th>${matches.map(match=>`<th>${escapeHTML(match.company.name)}</th>`).join('')}</tr></thead><tbody>${row('Score',matches.map(item=>`${item.score}/100`))}${row('Années reconnues',matches.map(item=>String(item.recognizedYears)))}${row('Traduction',matches.map(item=>item.translationRequired?'Requise*':'Non*'))}${row('Documents',matches.map(item=>String(item.documents.length)))}${row('Délai estimatif',matches.map(item=>`${item.processingDays} jours*`))}${row('Statut',matches.map(item=>item.verified?'Vérifié':item.status==='pending'?'À confirmer':'Démonstration'))}</tbody></table></div>`}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(item=>item!==id):[...state.favorites,id];saveState(state);if(lastMatches.length){$('#result-grid').innerHTML=lastMatches.map(resultCard).join('');bindResultActions()}toast('Favoris mis à jour localement');if(activeWorkspace==='favorites')renderWorkspace('favorites')}

function setupForm(){const form=$('#comparison-form');form.addEventListener('submit',event=>{event.preventDefault();const input=readForm(),errors=validate(input),error=$('#form-error');if(errors.length){error.textContent=errors.join(' ');error.focus();return}error.textContent='';renderResults(findMatches(input,catalog),input);$('#results-panel').scrollIntoView({behavior:'smooth',block:'start'})})}
function restoreHistory(item){if(!item?.input)return toast('Cette analyse ne contient pas de formulaire réutilisable');for(const[name,value]of Object.entries(item.input)){const field=$('#comparison-form').elements[name];if(!field)continue;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=value}renderResults(findMatches(readForm(),catalog),readForm(),{save:false});$('#comparateur').scrollIntoView({behavior:'smooth'})}
function historyView(){return state.history.length?`<div class="workspace-list">${state.history.slice(0,5).map(item=>`<article class="workspace-row history-row"><p>${escapeHTML(item.label)}<small>${new Date(item.at).toLocaleDateString('fr-FR')} · score ${Number(item.score||0)}/100 · ${escapeHTML(company(item.insurerId)?.name||'Assureur à confirmer')}</small></p><div><button type="button" data-review-history="${item.id}">Revoir</button><button type="button" data-remove-history="${item.id}" aria-label="Supprimer cette comparaison">Supprimer</button></div></article>`).join('')}</div>`:'<p class="workspace-empty">Aucune comparaison enregistrée dans ce navigateur.</p>'}
function favoriteView(){const items=state.favorites.map(company).filter(Boolean);return items.length?`<div class="workspace-list">${items.map(item=>`<article class="workspace-row"><img src="${escapeHTML(item.logo)}" alt=""><p>${escapeHTML(item.name)}<small>Assureur de démonstration · aucun partenariat officiel</small></p><button type="button" data-remove-favorite="${item.id}" aria-label="Retirer des favoris">×</button></article>`).join('')}</div>`:'<p class="workspace-empty">Aucun assureur favori.</p>'}
function documentsView(){const docs=profileDocuments();return`<div class="workspace-list">${Object.entries(docs).map(([id,status])=>`<article class="workspace-row"><p>${escapeHTML(documentNames[id])}<small>${escapeHTML(statusNames[status])}</small></p></article>`).join('')}<a class="button secondary" href="#documents">Mettre à jour la checklist</a></div>`}
function profileView(){const profile=activeProfile();return`<article class="profile-card"><img src="assets/logos/bonusbridge-symbol.svg" alt=""><div><span>PROFIL LOCAL · DÉMONSTRATION</span><h3>${escapeHTML(profile.name)}</h3><p>${escapeHTML(country(profile.originCountry)?.name||profile.originCountry)} → ${escapeHTML(country(profile.destinationCountry)?.name||profile.destinationCountry)} · ${escapeHTML(profile.role)} · ${profile.insuredYears??'Historique à compléter'}${profile.insuredYears?' ans':''}</p><small>${escapeHTML(profile.status)}</small></div><strong>${readiness()} % prêt</strong></article>`}
function settingsView(){return'<div class="workspace-settings"><button id="print-data" type="button">Télécharger mon résumé</button><button id="copy-summary" type="button">Copier le résumé</button><button id="export-data" type="button">Exporter mes données</button><label class="button secondary">Importer un JSON<input id="import-data" type="file" accept="application/json" hidden></label><button id="clear-data" type="button">Effacer les données locales</button></div>'}
function renderWorkspace(view=activeWorkspace){activeWorkspace=view;const content=$('#workspace-content');$$('[data-workspace]').forEach(button=>button.classList.toggle('active',button.dataset.workspace===view));if(view==='profile')content.innerHTML=profileView();if(view==='history')content.innerHTML=historyView();if(view==='favorites')content.innerHTML=favoriteView();if(view==='documents')content.innerHTML=documentsView();if(view==='settings')content.innerHTML=settingsView();$$('[data-remove-history]',content).forEach(button=>button.addEventListener('click',()=>{state.history=state.history.filter(item=>item.id!==button.dataset.removeHistory);saveState(state);renderWorkspace('history')}));$$('[data-review-history]',content).forEach(button=>button.addEventListener('click',()=>restoreHistory(state.history.find(item=>item.id===button.dataset.reviewHistory))));$$('[data-remove-favorite]',content).forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.removeFavorite)));$('#print-data')?.addEventListener('click',printSummary);$('#copy-summary')?.addEventListener('click',copySummary);$('#export-data')?.addEventListener('click',()=>exportJSON('bonusbridge-donnees-locales.json',exportableState(state)));$('#import-data')?.addEventListener('change',async event=>{try{mergeImportedState(state,await importJSON(event.target.files[0]));renderProfileOptions();updateIdentity();renderWorkspace('profile');toast('Données importées localement')}catch(error){toast(error.message)}});$('#clear-data')?.addEventListener('click',()=>{clearState();state=loadState();renderProfileOptions();applyProfileToForm();setupTheme(true);renderWorkspace('profile');toast('Données locales réinitialisées')})}
function setupWorkspace(){$$('[data-workspace]').forEach(button=>button.addEventListener('click',()=>renderWorkspace(button.dataset.workspace)));$('#profile-select').addEventListener('change',event=>{if(event.target.value==='new')return createProfile();state.activeProfileId=event.target.value;saveState(state);applyProfileToForm();syncChecklist();renderWorkspace('profile')});renderWorkspace()}
function createProfile(){const name=prompt('Nom du nouveau profil local :','Nouveau profil');if(!name?.trim()){renderProfileOptions();return}const id=`profile-${Date.now()}`;state.profiles.push({id,name:name.trim(),originCountry:'FR',destinationCountry:'CA',role:'Profil local',insuredYears:null,status:'À compléter',demo:true});state.documentsByProfile[id]={experience:'missing',information:'missing',licence:'missing',claims:'missing',translation:'missing',address:'missing',policy:'missing'};state.activeProfileId=id;saveState(state);renderProfileOptions();applyProfileToForm();syncChecklist();renderWorkspace('profile');toast('Nouveau profil créé dans ce navigateur')}

function syncChecklist(){const docs=profileDocuments();$$('[data-document]').forEach(input=>input.checked=docs[input.dataset.document]==='available');$$('[data-document-status]').forEach(select=>select.value=docs[select.dataset.documentStatus]||'missing');updateIdentity()}
function setupChecklist(){$$('[data-document]').forEach(input=>input.addEventListener('change',()=>{profileDocuments()[input.dataset.document]=input.checked?'available':'missing';$(`[data-document-status="${input.dataset.document}"]`).value=input.checked?'available':'missing';saveState(state);updateIdentity();if(activeWorkspace==='documents')renderWorkspace('documents')}));$$('[data-document-status]').forEach(select=>select.addEventListener('change',()=>{profileDocuments()[select.dataset.documentStatus]=select.value;$(`[data-document="${select.dataset.documentStatus}"]`).checked=select.value==='available';saveState(state);updateIdentity();if(activeWorkspace==='documents')renderWorkspace('documents')}));syncChecklist()}
function updateIdentity(){const profile=activeProfile(),docs=profileDocuments(),score=readiness(docs),available=Object.values(docs).filter(value=>value==='available').length,origin=country(profile.originCountry),destination=country(profile.destinationCountry);$('#hero-profile').textContent=profile.name;$('#hero-origin').textContent=`${origin?.flag||''} ${origin?.name||profile.originCountry}`;$('#hero-destination').textContent=`${destination?.flag||''} ${destination?.name||profile.destinationCountry}`;$('#hero-documents').textContent=`${available} sur 7`;$('#hero-readiness').textContent=`${score} %`;$('#hero-status').textContent=profile.status;$('#hero-progress').style.width=`${score}%`;$('#readiness-label').textContent=`Dossier prêt à ${score} %`;$('#readiness-bar').style.width=`${score}%`;renderWorkspace(activeWorkspace)}

function summaryText(){const profile=activeProfile(),docs=profileDocuments(),available=Object.keys(docs).filter(id=>docs[id]==='available').map(id=>documentNames[id]),missing=Object.keys(docs).filter(id=>docs[id]!=='available').map(id=>`${documentNames[id]} (${statusNames[docs[id]]})`),favorites=state.favorites.map(id=>company(id)?.name).filter(Boolean);return`BonusBridge — Résumé de démonstration\nProfil : ${profile.name}\nTrajet : ${country(profile.originCountry)?.name} → ${country(profile.destinationCountry)?.name}\nPréparation : ${readiness(docs)} %\nDocuments disponibles : ${available.join(', ')||'Aucun'}\nDocuments à traiter : ${missing.join(', ')||'Aucun'}\nAssureurs favoris : ${favorites.join(', ')||'Aucun'}\n\nDonnées de démonstration à confirmer directement auprès des assureurs. BonusBridge ne fournit pas de devis officiel.`}
async function copySummary(){const text=summaryText();try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove()}toast('Résumé copié dans le presse-papiers')}
function printSummary(){const profile=activeProfile(),docs=profileDocuments(),available=Object.keys(docs).filter(id=>docs[id]==='available'),missing=Object.keys(docs).filter(id=>docs[id]!=='available');$('#print-summary').innerHTML=`<img src="assets/logos/bonusbridge-logo.svg" alt="BonusBridge"><h1>Résumé du dossier</h1><h2>${escapeHTML(profile.name)} · ${escapeHTML(country(profile.originCountry)?.name)} → ${escapeHTML(country(profile.destinationCountry)?.name)}</h2><p class="print-score">Dossier prêt à ${readiness(docs)} %</p><h3>Documents disponibles</h3><ul>${available.map(id=>`<li>${escapeHTML(documentNames[id])}</li>`).join('')||'<li>Aucun</li>'}</ul><h3>Documents à traiter</h3><ul>${missing.map(id=>`<li>${escapeHTML(documentNames[id])} — ${escapeHTML(statusNames[docs[id]])}</li>`).join('')||'<li>Aucun</li>'}</ul><h3>Assureurs favoris</h3><p>${state.favorites.map(id=>escapeHTML(company(id)?.name)).filter(Boolean).join(', ')||'Aucun'}</p><footer>Données de démonstration à confirmer directement auprès des assureurs. BonusBridge ne fournit pas de devis officiel.</footer>`;window.print()}

function setupAssistant(){const dialog=$('#journey-assistant'),steps=$$('[data-assistant-step]',dialog),next=$('#assistant-next'),back=$('#assistant-back');let step=0;const render=()=>{steps.forEach((node,index)=>node.classList.toggle('active',index===step));$('#assistant-progress').style.width=`${((step+1)/steps.length)*100}%`;back.hidden=step===0;next.textContent=step===3?'Créer ma feuille de route':step===4?'Fermer':'Continuer'};const finish=()=>{const origin=$('#assistant-origin').value,destination=$('#assistant-destination').value,checked=$$('#assistant-documents input:checked').map(input=>input.value),rules=catalog.rules.filter(rule=>rule.originCountry===origin&&rule.destinationCountry===destination),recommended=['Lettre d’expérience','Relevé d’information','Permis de conduire','Historique des sinistres'],missing=recommended.filter((_,index)=>!checked.includes(['experience','information','licence','claims'][index])),score=Math.round(checked.length/4*100);$('#assistant-output').innerHTML=`<h3>${escapeHTML(country(origin)?.name)} → ${escapeHTML(country(destination)?.name)}</h3><p><strong>Préparation : ${score} %</strong></p><p>Documents recommandés : ${recommended.join(', ')}.</p><p>À compléter : ${missing.join(', ')||'aucun document principal'}.</p><p>Traduction : ${origin===destination?'probablement non':'à confirmer, probablement nécessaire selon la langue et l’assureur'}.</p><p>Étapes : obtenir les justificatifs, confirmer leur format, demander une étude écrite puis comparer les conditions.</p><p>Assureurs de démonstration compatibles : ${rules.map(rule=>company(rule.insurerId)?.name).filter(Boolean).join(', ')||'aucun scénario local disponible'}.</p><small>Aucune recommandation n’est une décision officielle d’assureur.</small>`};$('#open-assistant').addEventListener('click',()=>{const profile=activeProfile();$('#assistant-origin').value=profile.originCountry;$('#assistant-destination').value=profile.destinationCountry;step=0;render();dialog.showModal()});next.addEventListener('click',()=>{if(step===4)return dialog.close();if(step===3){finish();step=4}else step++;render()});back.addEventListener('click',()=>{if(step>0)step--;render()});$('#assistant-origin').addEventListener('change',event=>$('#assistant-destination').value=event.target.value==='FR'?'CA':'FR');render()}

const themeOrder=['dark','light','system'];
function applyTheme(){const preference=state.themePreference||'dark',resolved=preference==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):preference;document.documentElement.dataset.theme=resolved;$('#theme-toggle').textContent={dark:'◐ Sombre',light:'○ Clair',system:'◉ Système'}[preference];$$('img[src*="bonusbridge-dark.svg"],img[src*="bonusbridge-light.svg"]').forEach(image=>image.src=`assets/logos/bonusbridge-${resolved==='light'?'light':'dark'}.svg`)}
function setupTheme(reset=false){if(!reset)$('#theme-toggle').addEventListener('click',()=>{const index=themeOrder.indexOf(state.themePreference||'dark');state.themePreference=themeOrder[(index+1)%themeOrder.length];saveState(state);applyTheme()});applyTheme()}
const translations={en:{heroTitle:'Keep your insurance history when you move countries.',heroCopy:'BonusBridge compares insurers that may recognize your bonus, seniority and driving history internationally.',compareNow:'Compare now',seeInsurers:'View insurers'},fr:{heroTitle:'Conservez votre historique d’assurance lorsque vous changez de pays.',heroCopy:'BonusBridge compare les assureurs qui peuvent reconnaître votre bonus, votre ancienneté et votre historique de conduite à l’international.',compareNow:'Comparer maintenant',seeInsurers:'Voir les assureurs'}};
function setupLanguage(){let language='fr';$('#language-toggle').addEventListener('click',()=>{language=language==='fr'?'en':'fr';document.documentElement.lang=language;$$('[data-i18n]').forEach(node=>node.textContent=translations[language][node.dataset.i18n]);toast(language==='fr'?'Interface principale en français':'Main interface in English')})}
function setupNavigation(){const button=$('#menu-toggle'),nav=$('#main-nav');button.addEventListener('click',()=>{const open=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(open))});$$('#main-nav a').forEach(link=>link.addEventListener('click',()=>nav.classList.remove('open')));$$('[data-detail]').forEach(button=>button.addEventListener('click',()=>{toast('Fiche de démonstration — données à confirmer');$('#comparateur').scrollIntoView({behavior:'smooth'})}))}

async function init(){try{catalog=await loadCatalog();populate();setupTheme();setupForm();setupWorkspace();setupChecklist();setupAssistant();setupNavigation();setupLanguage();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(error){console.error(error);$('#form-error').textContent='Le catalogue interactif n’a pas pu être chargé. Le contenu principal reste accessible.'}}
init();
