import{loadCatalog}from'./data.js';
import{findMatches}from'../ai/matching.js';
import{loadState,saveState,clearState,addHistory,exportableState,mergeImportedState}from'./store.js';
import{exportJSON,importJSON}from'./export.js';

const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let catalog,state=loadState(),lastMatches=[];

function toast(message){const node=$('#toast');node.textContent=message;node.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.hidden=true,2800)}
function country(id){return catalog.countries.find(item=>item.id===id)}
function company(id){return catalog.companies.find(item=>item.id===id)}
function statusBadge(item){if(item.verified)return'<span class="badge verified">Vérifié</span>';if(item.status==='pending')return'<span class="badge pending">À confirmer</span>';return'<span class="badge demo">Démonstration</span>'}

function populate(){const countryOptions=catalog.countries.map(item=>`<option value="${item.id}">${item.flag} ${escapeHTML(item.name)}</option>`).join(''),coverageNames={'third-party':'Responsabilité civile','extended-third-party':'Tiers étendu','comprehensive':'Tous risques','premium-comprehensive':'Tous risques premium'},vehicleNames={compact:'Compacte',sedan:'Berline',suv:'SUV',electric:'Véhicule électrique',premium:'Véhicule premium',utility:'Utilitaire'};$('#origin-country').insertAdjacentHTML('beforeend',countryOptions);$('#destination-country').insertAdjacentHTML('beforeend',countryOptions);$('#current-company').insertAdjacentHTML('beforeend',catalog.companies.map(item=>`<option value="${item.id}">${escapeHTML(item.name)}</option>`).join(''));$('#coverage-type').insertAdjacentHTML('beforeend',catalog.coverages.map(item=>`<option value="${item.id}">${escapeHTML(coverageNames[item.id]||item.name)}</option>`).join(''));$('#vehicle-type').innerHTML=catalog.vehicles.map(item=>`<option value="${item.id}">${escapeHTML(vehicleNames[item.id]||item.name)}</option>`).join('');$('#origin-country').value='FR';$('#destination-country').value='CA';$('#current-company').value='pirez-assurance';$('#coverage-type').value='comprehensive';$('#vehicle-type').value='compact'}

function readForm(){const form=$('#comparison-form'),input=Object.fromEntries(new FormData(form));for(const key of['hasExperienceLetter','hasInformationStatement','hasClaimsHistory'])input[key]=form.elements[key].checked;input.mainDriver=true;input.youngDriver=false;return input}
function validate(input){const errors=[];for(const key of['originCountry','destinationCountry','currentCompany','insuredYears','bonusMalus','claimsCount','coverageType'])if(input[key]===''||input[key]==null)errors.push('Veuillez compléter tous les champs principaux.');if(input.originCountry===input.destinationCountry)errors.push('Les pays d’origine et de destination doivent être différents.');if(Number(input.insuredYears)<0||Number(input.insuredYears)>60)errors.push('L’ancienneté doit être comprise entre 0 et 60 ans.');if(Number(input.claimsCount)<0||Number(input.claimsCount)>20)errors.push('Le nombre de sinistres doit être compris entre 0 et 20.');return[...new Set(errors)]}

function resultCard(match){const logo=match.company.logo||'./assets/logos/bonusbridge-symbol.svg';return`<article class="insurer-card"><img src="${escapeHTML(logo)}" alt="Logo ${escapeHTML(match.company.name)}"><div><span>${escapeHTML(country(match.rule.destinationCountry)?.name||match.rule.destinationCountry)} · ${match.recognized?'Historique accepté*':'Non accepté*'}</span><h3>${escapeHTML(match.company.name)}</h3></div><dl><div><dt>Compatibilité</dt><dd>${match.score}/100</dd></div><div><dt>Années reconnues</dt><dd>${match.recognizedYears} max.</dd></div><div><dt>Bonus conservé</dt><dd>${match.recognizedBonus}%*</dd></div><div><dt>Traduction</dt><dd>${match.translationRequired?'Requise*':'Non*'}</dd></div></dl>${statusBadge(match)}<button type="button" data-favorite="${escapeHTML(match.company.id)}">${state.favorites.includes(match.company.id)?'Retirer des favoris':'Ajouter aux favoris'}</button></article>`}
function renderResults(matches,input){const grid=$('#result-grid'),summary=$('#results-summary');lastMatches=matches;if(!matches.length){summary.textContent='Aucune règle locale disponible pour ce trajet.';grid.innerHTML='<article class="empty-state"><strong>Aucun scénario disponible.</strong><p>Ce résultat ne signifie pas que votre historique sera refusé. Contactez directement les assureurs de destination.</p></article>';return}summary.textContent=`${matches.length} scénario${matches.length>1?'s':''} de démonstration · meilleur score ${matches[0].score}/100`;grid.innerHTML=matches.slice(0,6).map(resultCard).join('');$$('[data-favorite]',grid).forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.favorite)));addHistory(state,`${country(input.originCountry)?.name} → ${country(input.destinationCountry)?.name}`,`${input.originCountry}-${input.destinationCountry}`,matches[0].score,input);renderWorkspace('history')}

function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(item=>item!==id):[...state.favorites,id];saveState(state);if(lastMatches.length)$('#result-grid').innerHTML=lastMatches.map(resultCard).join('');$$('[data-favorite]').forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.favorite)));toast('Favoris mis à jour localement');renderWorkspace('favorites')}

function setupForm(){const form=$('#comparison-form');form.addEventListener('submit',event=>{event.preventDefault();const input=readForm(),errors=validate(input),error=$('#form-error');if(errors.length){error.textContent=errors.join(' ');error.focus();return}error.textContent='';renderResults(findMatches(input,catalog),input);$('#results-panel').scrollIntoView({behavior:'smooth',block:'start'})})}

function historyView(){return state.history.length?`<div class="workspace-list">${state.history.slice(0,8).map(item=>`<article class="workspace-row"><p>${escapeHTML(item.label)}<small>${new Date(item.at).toLocaleDateString('fr-FR')} · score ${Number(item.score||0)}/100</small></p><button type="button" data-remove-history="${item.id}" aria-label="Supprimer cette comparaison">×</button></article>`).join('')}</div>`:'<p class="workspace-empty">Aucune comparaison enregistrée dans ce navigateur.</p>'}
function favoriteView(){const items=state.favorites.map(company).filter(Boolean);return items.length?`<div class="workspace-list">${items.map(item=>`<article class="workspace-row"><img src="${escapeHTML(item.logo)}" alt=""><p>${escapeHTML(item.name)}<small>Assureur de démonstration</small></p><button type="button" data-remove-favorite="${item.id}" aria-label="Retirer des favoris">×</button></article>`).join('')}</div>`:'<p class="workspace-empty">Aucun assureur favori.</p>'}
function documentsView(){return'<div class="workspace-list"><article class="workspace-row"><p>Lettre d’expérience<small>Statut local : à préparer</small></p></article><article class="workspace-row"><p>Relevé d’information<small>Statut local : à vérifier</small></p></article><article class="workspace-row"><p>Permis de conduire<small>Statut local : disponible</small></p></article></div>'}
function renderWorkspace(view='profile'){const content=$('#workspace-content');$$('[data-workspace]').forEach(button=>button.classList.toggle('active',button.dataset.workspace===view));if(view==='profile')content.innerHTML=`<article class="profile-card"><img src="assets/logos/bonusbridge-symbol.svg" alt=""><div><span>PROFIL LOCAL</span><h3>${escapeHTML(state.profile.name||'Conducteur international')}</h3><p>Aucune donnée n’est envoyée vers un serveur.</p></div><strong>${state.history.length} comparaison${state.history.length>1?'s':''}</strong></article>`;if(view==='history')content.innerHTML=historyView();if(view==='favorites')content.innerHTML=favoriteView();if(view==='documents')content.innerHTML=documentsView();if(view==='settings')content.innerHTML='<div class="workspace-settings"><button id="export-data" type="button">Exporter mes données</button><label class="button secondary">Importer un JSON<input id="import-data" type="file" accept="application/json" hidden></label><button id="clear-data" type="button">Effacer les données locales</button></div>';$$('[data-remove-history]',content).forEach(button=>button.addEventListener('click',()=>{state.history=state.history.filter(item=>item.id!==button.dataset.removeHistory);saveState(state);renderWorkspace('history')}));$$('[data-remove-favorite]',content).forEach(button=>button.addEventListener('click',()=>{state.favorites=state.favorites.filter(item=>item!==button.dataset.removeFavorite);saveState(state);renderWorkspace('favorites')}));$('#export-data')?.addEventListener('click',()=>exportJSON('bonusbridge-donnees-locales.json',exportableState(state)));$('#import-data')?.addEventListener('change',async event=>{try{mergeImportedState(state,await importJSON(event.target.files[0]));renderWorkspace('profile');toast('Données importées localement')}catch(error){toast(error.message)}});$('#clear-data')?.addEventListener('click',()=>{clearState();state=loadState();renderWorkspace('profile');toast('Données locales effacées')})}
function setupWorkspace(){$$('[data-workspace]').forEach(button=>button.addEventListener('click',()=>renderWorkspace(button.dataset.workspace)));renderWorkspace()}

const translations={en:{heroTitle:'Keep your insurance history when you move countries.',heroCopy:'BonusBridge compares insurers that may recognize your bonus, seniority and driving history internationally.',compareNow:'Compare now',seeInsurers:'View insurers'},fr:{heroTitle:'Conservez votre historique d’assurance lorsque vous changez de pays.',heroCopy:'BonusBridge compare les assureurs qui peuvent reconnaître votre bonus, votre ancienneté et votre historique de conduite à l’international.',compareNow:'Comparer maintenant',seeInsurers:'Voir les assureurs'}};
function setupLanguage(){let language='fr';$('#language-toggle').addEventListener('click',()=>{language=language==='fr'?'en':'fr';document.documentElement.lang=language;$$('[data-i18n]').forEach(node=>node.textContent=translations[language][node.dataset.i18n]);toast(language==='fr'?'Interface principale en français':'Main interface in English')})}
function setupNavigation(){const button=$('#menu-toggle'),nav=$('#main-nav');button.addEventListener('click',()=>{const open=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(open))});$$('#main-nav a').forEach(link=>link.addEventListener('click',()=>nav.classList.remove('open')));$$('[data-detail]').forEach(button=>button.addEventListener('click',()=>{toast('Fiche de démonstration — données à confirmer');$('#comparateur').scrollIntoView({behavior:'smooth'})}))}

async function init(){try{catalog=await loadCatalog();populate();setupForm();setupWorkspace();setupNavigation();setupLanguage();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(error){console.error(error);$('#form-error').textContent='Le catalogue interactif n’a pas pu être chargé. Le contenu principal reste accessible.'}}
init();
