const KEY='bonusbridge-v3';
const demoProfiles=[
  {id:'jeremy',name:'Jérémy',originCountry:'FR',destinationCountry:'CA',role:'Conducteur principal',insuredYears:8,status:'Dossier en préparation',demo:true},
  {id:'julia',name:'Julia',originCountry:'CA',destinationCountry:'FR',role:'Profil familial',insuredYears:null,status:'Documents à préparer',demo:true}
];
const jeremyDocuments={experience:'available',information:'available',licence:'available',claims:'missing',translation:'translation',address:'available',policy:'available'};
const juliaDocuments={experience:'missing',information:'missing',licence:'available',claims:'missing',translation:'translation',address:'missing',policy:'missing'};
const defaults={theme:'dark',themePreference:'dark',history:[],favorites:[],savedComparisons:[],localRuleEdits:[],profiles:demoProfiles,activeProfileId:'jeremy',documentsByProfile:{jeremy:jeremyDocuments,julia:juliaDocuments},profile:{name:'Jérémy',country:'FR',currency:'EUR',language:'fr'}};
const cleanArray=value=>Array.isArray(value)?value:[];
const clone=value=>structuredClone(value);
export function loadState(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');const profiles=cleanArray(saved.profiles).length?saved.profiles:clone(demoProfiles);return{...clone(defaults),...saved,history:cleanArray(saved.history).slice(0,5),favorites:cleanArray(saved.favorites),savedComparisons:cleanArray(saved.savedComparisons),localRuleEdits:cleanArray(saved.localRuleEdits),profiles,activeProfileId:profiles.some(item=>item.id===saved.activeProfileId)?saved.activeProfileId:profiles[0].id,documentsByProfile:{...clone(defaults.documentsByProfile),...(saved.documentsByProfile||{})},profile:{...defaults.profile,...saved.profile}}}catch{return clone(defaults)}}
export function saveState(state){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{return false}}
export function clearState(){localStorage.removeItem(KEY)}
export function addHistory(state,label,route,score,input={},insurerId=''){state.history.unshift({id:crypto.randomUUID?.()||String(Date.now()),label,route,score,input,insurerId,at:new Date().toISOString()});state.history=state.history.slice(0,5);saveState(state)}
export function exportableState(state){return{schemaVersion:'4.1.0',exportedAt:new Date().toISOString(),application:'BonusBridge',data:{history:state.history,favorites:state.favorites,savedComparisons:state.savedComparisons,profile:state.profile,profiles:state.profiles,activeProfileId:state.activeProfileId,documentsByProfile:state.documentsByProfile,themePreference:state.themePreference,localRuleEdits:state.localRuleEdits}}}
export function mergeImportedState(state,payload){if(payload.application!=='BonusBridge'||!payload.data)throw new Error('Ce fichier n’est pas un export BonusBridge valide.');for(const key of['history','favorites','savedComparisons','localRuleEdits','profiles'])if(payload.data[key]&&!Array.isArray(payload.data[key]))throw new Error(`Collection ${key} invalide.`);Object.assign(state,{history:(payload.data.history||[]).slice(0,5),favorites:payload.data.favorites||[],savedComparisons:payload.data.savedComparisons||[],localRuleEdits:payload.data.localRuleEdits||[],profiles:payload.data.profiles?.length?payload.data.profiles:state.profiles,activeProfileId:payload.data.activeProfileId||state.activeProfileId,documentsByProfile:payload.data.documentsByProfile||state.documentsByProfile,themePreference:payload.data.themePreference||state.themePreference,profile:{...defaults.profile,...payload.data.profile}});saveState(state);return state}
